Wrote The Talon Concepts -> Settings Section
TalonCommunity/Wiki pull request #160
Opened 2022-02-27 04:34 UTC by AndrewDant

2022-02-27 05:29 UTC, splondike reviewed
Looks good, thanks! Just that one thing to add in I think.

I also noticed the use of 'talon user file set' ;).

2022-02-27 05:29 UTC, splondike commented on unofficial_talon_docs.md
> +)
Should also include how to read the setting out (`horizontal_position.get()`).

2022-02-27 05:55 UTC, AndrewDant commented on unofficial_talon_docs.md
> +)
Good catch, I definitely meant to include that.

2022-02-28 22:56 UTC, tararoys requested changes
Line 743 is missing a comma at the end of `default=0`

Apart from that, a useful overview!  

It *might* be worth mentioning that setting ocks are fragile compared to the rest of Talon's syntax.

In Talon files, an error anywhere in the settings block will disable every setting that has been set in that settings block.  (I tested this by introducing errors into the settings block of my dense mouse grid and a syntax setting change anywhere in the block made it revert back to my defaults.)

2022-02-28 23:47 UTC, splondike commented
That fragility may be a feature. I imagine you could want the whole group of settings to apply atomically, if it were partially applied you might get unexpected results.

Happy with either having it in or not as per Andrew's preference.

2022-03-01 01:22 UTC, AndrewDant commented
I've implemented the changes suggested by [tararoys](https://github.com/tararoys)

2022-03-02 01:28 UTC, merged

2022-03-02 01:29 UTC, splondike commented
Thanks!